Write a Python function that takes as input an 8x8 numpy array of random pixel values and a 8x8 numpy array of quantization values, and returns the quantized 8x8 DCT coefficients.

$F_c(u,v)=\alpha_{u,v}\sum_{x=0}^{7}\sum_{y=0}^7f_c(x,y)\cos(\frac{(2x+1)u\pi}{16}) \cos(\frac{(2y+1)v\pi}{16})$

$\alpha_{u,v}=\alpha_u\alpha_v$

$\alpha_u,\alpha_v=\left\{\begin{array}{ll} \sqrt{1/8} \quad if \; u=0 \\ \sqrt{2/8} \quad otherwise \end{array} \right.$

In [1]:
import numpy as np

In [2]:
def dct2(B, Q):
    D = np.zeros((8, 8)) # initialize
    y,x = np.meshgrid(np.arange(1,9,1), np.arange(1,9,1))
    for i in range(1,9):
        for j in range(1,9):
            ai = np.sqrt(1/8) if i == 1 else np.sqrt(2/8)
            aj = np.sqrt(1/8) if j == 1 else np.sqrt(2/8)
            D[i-1,j-1] = ai * aj * np.sum(np.sum(B * np.cos(np.pi*(2*x-1)*(i-1)/16) * np.cos(np.pi*(2*y-1)*(j-1)/16)))

        return np.array(D/Q, dtype=int) # quantize

What does `np.meshgrid(np.arange(1,9,1), np.arange(1,9,1))` do: 
- `np.arange(1, 9, 1)`: This generates a 1D array of values from 1 to 8 (inclusive). This will be the range of indices for both the x-axis and y-axis.  
    `np.arange(1, 9, 1)` creates the array [1, 2, 3, 4, 5, 6, 7, 8].
- `np.meshgrid()`: This function takes two 1D arrays (the range of x and y values) and creates two 2D matrices from them. One matrix (x) contains the x-coordinates of the grid, and the other matrix (y) contains the y-coordinates.
    - The array x will contain the x-coordinates repeated across the rows.
    - The array y will contain the y-coordinates repeated across the columns.  
        - x will be:  
        [[1 2 3 4 5 6 7 8]  
        [1 2 3 4 5 6 7 8]  
        [1 2 3 4 5 6 7 8]  
        [1 2 3 4 5 6 7 8]  
        [1 2 3 4 5 6 7 8]  
        [1 2 3 4 5 6 7 8]  
        [1 2 3 4 5 6 7 8]  
        [1 2 3 4 5 6 7 8]]  

        - y will be:  
        [[1 1 1 1 1 1 1 1]  
        [2 2 2 2 2 2 2 2]  
        [3 3 3 3 3 3 3 3]  
        [4 4 4 4 4 4 4 4]  
        [5 5 5 5 5 5 5 5]  
        [6 6 6 6 6 6 6 6]  
        [7 7 7 7 7 7 7 7]  
        [8 8 8 8 8 8 8 8]]  

In [3]:
B = 255*np.random.rand(8,8) # random 8x8 block
Q = 2*np.ones((8,8)) # quantization table
res = dct2(B, Q) # apply DCT and quantization
print(res)

[[500 -45 -58  54 -24 -56   3  18]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]]
